import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar/Navbar";
import Sidebar from "../components/Navbar/Sidebar/Sidebar";
import styles from "../styles/Home.module.css";

export default function Home() {
	return (
		<div className="flex flex-col p-2 h-screen w-screen">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar/>
			
			

			<main className="flex flex-row h-full">
				<Sidebar />
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{" "}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
}
